title: "Sturmius Tuschmann"
author: "Sturmius Tuschmann"
description: "s.tuschmann23@imperial.ac.uk"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {url: "(/CV.pdf)", title: "CV"}
  - {url: "https://www.linkedin.com/in/sturmius-tuschmann", title: "LinkedIn"}
  - {url: "https://scholar.google.com/citations?user=MB8iSvUAAAAJ&hl=en", title: "Google Scholar"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:s.tuschmann23@imperial.ac.uk"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/sturmius-tuschmann"}
  - {title: Google Scholar, icon: google, url: "https://scholar.google.com/citations?user=MB8iSvUAAAAJ&hl=en"}
  - {title: Github, icon: github, url: "https://github.com/tuschmann"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
